config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "feed#show"

  # Users routes
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  resource :profile, only: %i[ show update ], controller: "users"

  # Route user password changes to users/passwords_controller update action
  namespace :users do
    patch "change_password", to: "passwords#update"
  end

  # Sessions routes
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Include Authenticate concern.  It helps with user authenication in all controllers
  include Authenticate

  # Turbo adds a Turbo-Frame HTTP header when a request originates from within a Turbo Frame.
  # The turbo-rails gem has a method called turbo_frame_request? that checks if this header exists.
  # It’s not exposed as a helper method though, so it needs to be declared as such
  helper_method :turbo_frame_request?

  # The turbo-rails gem has a turbo_native_app? method which matches the user agent of the request
  # with the string "Turbo Native". This method first needs to be exposed as a helper method and
  # then it can be used to hide the desktop's navigation bar
  helper_method :turbo_native_app?
end

app/helpers/application_helper.rb
module ApplicationHelper
  #
  # In this app, each page will have a title [helps SEO].
  # If a title isn't specified, this method sets a default.
  # NOTE:  All titles and user-facing text is managed by internationalization (i18n) files.
  def title
    return t("piazza") unless content_for?(:title)
    # If running native app, don't inlcude "piazza" suffix as user knows they started app piazza
    return content_for(:title) if turbo_native_app?

    "#{content_for(:title)} | #{t("piazza")}"
  end
end

app/views/application/_flash_messages.html.erb
<%# locals: () -%>

<!-- 
  data-turbo-temporary is specified on the container element to prevent
  Turbo from caching the alert during navigation. Without this attribute, users
  will see the alert for a fraction of a second before it disappears if they
  navigate back to a page with a flash after having navigated away due to
  Turbo’s local cache.
-->
<div class="container is-fluid" data-turbo-temporary>
  <% flash.each do |level, message| %>
    <%= tag.div \
      class: "notification is-#{level} is-light has-text-centered mt-4" do %>

        <%= message %>

    <% end %>
  <% end %>
</div>

app/views/application/_form_errors.html.erb
<%# locals: (html_tag:, instance:) -%>

<% unless html_tag =~ /^<label/ %>
  <% field_html = Nokogiri::HTML::DocumentFragment.parse(html_tag) %>
  <% field_html.children.add_class("is-danger") %>

  <!--  Using == instead of = prevents the HTML from being escaped so it
        executes and doesn’t render on screen as code. -->
  <%== field_html %>

  <p class="help is-danger">
    <%= instance.error_message.to_sentence %>
  </p>
<% else %>
  <%= html_tag %>
<% end %>

app/views/application/_navbar.html.erb
<%# locals: () -%>

<nav class="navbar is-link" data-controller="navbar">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <strong class="is-size-3">Piazza</strong>
    <% end %>
    <a role="button" 
       class="navbar-burger" 
       data-navbar-target="burgerMenuButton"
       data-action="navbar#toggle">
      <!-- The 4 spans below are for the three lines of the burger menu icon -->
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </a>
  </div>

  <div class="navbar-menu" data-navbar-target="menuDropdown">
    <div class="navbar-start">
      <%= link_to t(".create_ad"), "#", class: "navbar-item" %>
      <% if logged_in? %>
        <%= link_to t(".messages"), "#", class: "navbar-item" %>
      <% end %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">

        <div class="buttons">
          <% if logged_in? %>

            <div class="navbar-item has-dropdown is-hoverable mr-4">
              <%# The id: below is used to enable a turbo_stream to update user name in navbar after %>
              <%# the user edits it in their profile %>
              <%= link_to Current.user.name, 
                          profile_path, 
                          id: "current_user_name",
                          class: "navbar-link" %>
                          
              <div class="navbar-dropdown is-right">
                <%= link_to t(".profile"), profile_path, class: "navbar-item" %>
                <%= link_to t(".my_ads"), "#", class: "navbar-item" %>
                <%= link_to t(".saved_ads"), "#", class: "navbar-item" %>
                <hr class="navbar-divider">
                <%= link_to t(".logout"), 
                      logout_path, 
                      class: "navbar-item", 
                      data: { turbo_method: :delete } %>
            </div>
            
          <% else %>
            <%= link_to t(".sign_up"), sign_up_path, class: "button is-primary" %>
            <%= link_to t(".login"), login_path, class: "button is-light" %>
          <% end %>

        </div>

      </div>

    </div>
  </div>
</nav>